on: [push]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      run: |
        sudo apt update
        sudo apt install nodejs
        sudo apt install npm
        npm install
    - name: Hexo Generate
      run: |
        hexo g
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

